name: "Common OpenTofu Setup"
description: "Checkout and setup OpenTofu and Bitwarden CLI"
inputs:
  download_bw:
    description: "Wether to download the bw cli"
    default: "true"
    required: false
  github_token:
    description: "A github token used to download the bw cli"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1
      with:
        tofu_version: 1.10.6

    - name: Download Bitwarden CLI ${{ env.BW_VERSION }}
      shell: bash
      if: inputs.download_bw == true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        BW_VERSION: 2025.9.0
      run: |
        URL="https://github.com/bitwarden/clients/releases/download/cli-v${BW_VERSION}/bw-linux-${BW_VERSION}.zip"
        curl -L -H "Authorization: Bearer ${GITHUB_TOKEN}" -o bw.zip "$URL"
        sudo unzip -o bw.zip -d /usr/local/bin
        sudo chmod +x /usr/local/bin/bw
        bw --version
