name: "OpenTofu Plan"
description: "Run OpenTofu plan"
inputs:
  github_token:
    description: "A github token used to download the bw cli"
    required: true
outputs:
  plan:
    description: Stdout of tofu plan command
    value: ${{ steps.plan.outputs.stdout }}
  plan_outcome:
    description: Outcome of tofu plan command
    value: ${{ steps.plan.outcome }}
  validate:
    description: Stdout of tofu validate command
    value: ${{ steps.validate.outputs.stdout }}
  validate_outcome:
    description: Outcome of tofu validate command
    value: ${{ steps.validate.outcome }}
  init_outcome:
    description: Outcome of tofu init command
    value: ${{ steps.init.outcome }}
runs:
  using: "composite"
  steps:
    - name: Common Setup
      uses: ./.github/actions/common-setup
      with:
        github_token: ${{ inputs.github_token }}

    - name: OpenTofu Init
      shell: bash
      working-directory: tofu
      id: init
      run: tofu init

    - name: OpenTofu Validate
      shell: bash
      working-directory: tofu
      id: validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      shell: bash
      working-directory: tofu
      id: plan
      run: tofu plan -no-color -out=tfplan
